export const actionsTypes = {
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  FETCH_MEAL_BY_SEARCH_VALUE: "FETCH_MEAL_BY_SEARCH_VALUE",
  CHAGE_PAGE_NUMBER: "CHAGE_PAGE_NUMBER",
  FETCH_MEALS_BY_CATEGOREY: "FETCH_MEALS_BY_CATEGOREY",
  CLEAN_MEALS_BY_CATEGOREY: "CLEAN_MEALS_BY_CATEGOREY",
};
